version: '3.2'

services:
  monitoring:
    container_name: system-sensors
    build: .
    restart: always
    devices:
      - /dev/vchiq
    volumes:
      - ./config:/app/config
      - /etc/os-release:/app/host/os-release:ro
      - /etc/hostname:/app/host/hostname:ro
      - /opt/vc:/opt/vc:ro
      - /proc/device-tree/model:/app/host/proc/device-tree/model:ro
      - /tmp/system_sensor_pipe:/app/host/system_sensor_pipe:ro
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
